### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Majber** [ericfitzgerald/KingmakerCharacterEditor#3]
I hope that you will update this editor to latest version of game and add sth like spell/abilities edition.

**Comment by ericfitzgerald** [comment]
Newest update should work, but I think there might be a small issue with the zip file. I'm looking into better ways to package that.

**Comment by Majber** [comment]
Thank you for update, its all working now. Would you consider updating this project even more? Maybe adding feats or sth?

**Comment by Lordspurs** [comment]
Is there a way to edit Octavia and Regongar's stats? I don't see them in the edit table.

**Comment by ericfitzgerald** [comment]
Octavia and Regongar should be on there but I haven't yet got them on my local save file so I don't know their unique ID's.  They should so as entries with a guid instead of a name.  Just look for matching stats.

As to adding feats, that's a lot harder than it sounds.  Feats are added through GUID's and I need to know those GUID's before hand.  If you have the feat somewhere in your save file that's easy enough to do, but if not I would need to have it known in the application.  If someone wants to start working to compile a list of feat guid's I could build it in though.

**Comment by Lordspurs** [comment]
I have dots underneath Amiri, but no info when I open the character creation tool app.

**Comment by ericfitzgerald** [comment]
Can you send a screenshot of that?  I'm not sure what you are seeing.

**Comment by Lordspurs** [comment]
![cc](https://user-images.githubusercontent.com/43704500/46248634-bf6fd480-c413-11e8-9a27-7f50bdcd0716.png)

**Comment by ericfitzgerald** [comment]
Okay so it is seeing characters with no stats.  Can you possible send me the save file you are trying to edit so I can see what is tripping it up?

**Comment by Lordspurs** [comment]
I think the problem, may be linked to me trying to create companion characters, but being stopped by the bug, could that be it?

**Comment by ericfitzgerald** [comment]
Ahh that guy.  I haven't played with him.  Yeah please send me the save file so I can make it able to handle that guy.  For now I'll have it ignore those but I need to see what they look like so that the system doesn't crash when you have them in your party.

**Comment by Lordspurs** [comment]
Can I send it in a private message of any kind? (sorry I'm new to this forum).

**Comment by ericfitzgerald** [comment]
Yes, you can e-mail it directly to me.  thefitz_2@yahoo.com

**Comment by Lordspurs** [comment]
[Manual_1_Acehilm.zip](https://github.com/ericfitzgerald/KingmakerCharacterEditor/files/2430892/Manual_1_Acehilm.zip)

**Comment by ericfitzgerald** [comment]
Working on it now, give me a few minutes to figure out what's happening and I'll have it fixed

**Comment by Lordspurs** [comment]
Thank you!!

**Comment by ericfitzgerald** [comment]
Fixed and new release uploaded

**Comment by Lordspurs** [comment]
You're brilliant! Thanks!
